import React from "react";
import Head from "next/head";

type Props = {
  title: any;
  href: string;
};

const HeadTitle = (props: Props) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
      <link rel="icon" href={props.href} />
    </Head>
  );
};

export default HeadTitle;
